CREATE TABLE ERS_USERS (
    ERS_USERS_ID NUMBER PRIMARY KEY,
    ERS_USERNAME VARCHAR2(50) UNIQUE NOT NULL,
    ERS_PASSWORD VARCHAR2(50) UNIQUE NOT NULL,
    USER_FIRST_NAME VARCHAR(100),
    USER_LAST_NAME VARCHAR(100),
    USER_EMAIL VARCHAR(150),
    USER_ROLE_ID NUMBER,
    CONSTRAINT USER_ROLES_FK
    FOREIGN KEY (USER_ROLE_ID)
    REFERENCES ERS_USER_ROLES(ERS_USER_ROLE_ID)
);
commit;

CREATE TABLE ERS_USER_ROLES(
    ERS_USER_ROLE_ID NUMBER PRIMARY KEY,
    USER_ROLE VARCHAR2(10)
);


CREATE TABLE ERS_REIMBURSEMENT(
    REIMB_ID NUMBER PRIMARY KEY,
    REIMB_AMOUNT NUMBER,
    REIMB_SUBMITTED TIMESTAMP,
    REIMB_RESOLVED TIMESTAMP,
    REIMB_DESCRIPTION VARCHAR2(250),
    REIMB_RECEIPT BLOB,
    REIMB_AUTHOR NUMBER,
    REIMB_RESOLVER NUMBER,
    REIMB_STATUS_ID NUMBER,
    REIMB_TYPE_ID NUMBER,
    CONSTRAINT ERS_USERS_FK_AUTH FOREIGN KEY (REIMB_AUTHOR) REFERENCES ERS_USERS(ERS_USERS_ID),
    CONSTRAINT ERS_USERS_FK_RESOLVER FOREIGN KEY (REIMB_RESOLVER) REFERENCES ERS_USERS(ERS_USERS_ID),
    CONSTRAINT ERS_REIMBURSEMENT_STATUS_FK FOREIGN KEY (REIMB_STATUS_ID) REFERENCES ERS_REIMBURSEMENT_STATUS(REIMB_STATUS_ID),----
    CONSTRAINT ERS_REIMBURSEMENT_TYPE_FK FOREIGN KEY (REIMB_TYPE_ID) REFERENCES ERS_REIMBURSEMENT_TYPE(REIMB_TYPE_ID)----
);


CREATE TABLE ERS_REIMBURSEMENT_STATUS(
    REIMB_STATUS_ID NUMBER PRIMARY KEY,
    REIMB_STATUS VARCHAR2(10)
);

CREATE TABLE ERS_REIMBURSEMENT_TYPE(
    REIMB_TYPE_ID NUMBER PRIMARY KEY,
    REIMB_TYPE VARCHAR2(10)
);

drop table ERS_REIMBURSEMENT_TYPE;
drop table ERS_REIMBURSEMENT_STATUS;
drop table ERS_REIMBURSEMENT;
drop table ERS_USER_ROLES;
drop table ERS_USERS;

commit;










